<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SnapshotDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Tabla: roles
        DB::table('roles')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Admin',
                'descripcion' => 'Administrador del sistema',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Juez',
                'descripcion' => 'Encargado de calificar proyectos',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Participante',
                'descripcion' => 'Miembro de un equipo',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);

        // Tabla: carreras
        DB::table('carreras')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Contador Público',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Licenciatura en Administración',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Ingeniería Química',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'nombre' => 'Ingeniería Mecánica',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'nombre' => 'Ingeniería Industrial',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'nombre' => 'Ingeniería en Sistemas Computacionales',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'nombre' => 'Ingeniería en Gestión Empresarial',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'nombre' => 'Ingeniería Electrónica',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'nombre' => 'Ingeniería Eléctrica',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            9 => [
                'id' => 10,
                'nombre' => 'Ingeniería Civil',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);

        // Tabla: perfiles
        DB::table('perfiles')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Líder de Proyecto',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Programador Backend',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Programador Frontend',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'nombre' => 'Diseñador UI/UX',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'nombre' => 'Tester de Calidad',
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);

        // Tabla: categorias
        DB::table('categorias')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Aplicación Web',
                'descripcion' => 'Proyectos de aplicaciones web desarrolladas con tecnologías modernas',
                'icono' => 'bi-globe',
                'color' => '#667eea',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Aplicación Móvil',
                'descripcion' => 'Aplicaciones para dispositivos móviles (iOS, Android)',
                'icono' => 'bi-phone',
                'color' => '#764ba2',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Inteligencia Artificial',
                'descripcion' => 'Proyectos que utilizan IA, Machine Learning o Deep Learning',
                'icono' => 'bi-robot',
                'color' => '#f093fb',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            3 => [
                'id' => 4,
                'nombre' => 'Internet de las Cosas (IoT)',
                'descripcion' => 'Proyectos de hardware conectado y sistemas embebidos',
                'icono' => 'bi-cpu',
                'color' => '#4facfe',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            4 => [
                'id' => 5,
                'nombre' => 'Videojuegos',
                'descripcion' => 'Desarrollo de videojuegos y experiencias interactivas',
                'icono' => 'bi-controller',
                'color' => '#43e97b',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            5 => [
                'id' => 6,
                'nombre' => 'Blockchain',
                'descripcion' => 'Proyectos basados en tecnología blockchain y criptomonedas',
                'icono' => 'bi-link-45deg',
                'color' => '#fa709a',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            6 => [
                'id' => 7,
                'nombre' => 'Ciberseguridad',
                'descripcion' => 'Herramientas y soluciones de seguridad informática',
                'icono' => 'bi-shield-check',
                'color' => '#e74c3c',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            7 => [
                'id' => 8,
                'nombre' => 'Realidad Virtual/Aumentada',
                'descripcion' => 'Experiencias inmersivas en VR o AR',
                'icono' => 'bi-badge-vr',
                'color' => '#9b59b6',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            8 => [
                'id' => 9,
                'nombre' => 'Educación',
                'descripcion' => 'Plataformas y herramientas educativas',
                'icono' => 'bi-book',
                'color' => '#3498db',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            9 => [
                'id' => 10,
                'nombre' => 'Salud',
                'descripcion' => 'Soluciones tecnológicas para el sector salud',
                'icono' => 'bi-heart-pulse',
                'color' => '#e74c3c',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            10 => [
                'id' => 11,
                'nombre' => 'Sostenibilidad',
                'descripcion' => 'Proyectos enfocados en medio ambiente y sostenibilidad',
                'icono' => 'bi-tree',
                'color' => '#27ae60',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
            11 => [
                'id' => 12,
                'nombre' => 'Fintech',
                'descripcion' => 'Tecnología financiera e innovación en servicios financieros',
                'icono' => 'bi-currency-dollar',
                'color' => '#f39c12',
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
            ],
        ]);

        // Tabla: eventos
        DB::table('eventos')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Hackatón IoT para el Campus',
                'descripcion' => 'Desarrollo de soluciones conectadas para optimizar los recursos universitarios.',
                'fecha_inicio' => '2025-12-14',
                'fecha_fin' => '2025-12-16',
                'estado' => 'proximo',
                'max_equipos' => 20,
                'categoria_id' => 1,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Concurso de Diseño UX/UI',
                'descripcion' => 'Diseña la mejor interfaz para una aplicación móvil de servicios estudiantiles.',
                'fecha_inicio' => '2025-11-29',
                'fecha_fin' => '2025-12-06',
                'estado' => 'finalizado',
                'max_equipos' => 15,
                'categoria_id' => 1,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Desarrollo de Apps Móviles',
                'descripcion' => 'Crea una aplicación móvil innovadora que resuelva un problema real.',
                'fecha_inicio' => '2025-12-07',
                'fecha_fin' => '2025-12-14',
                'estado' => 'activo',
                'max_equipos' => 25,
                'categoria_id' => 1,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'nombre' => 'Inteligencia Artificial Challenge',
                'descripcion' => 'Desarrolla soluciones basadas en IA para resolver problemas complejos.',
                'fecha_inicio' => '2025-12-24',
                'fecha_fin' => '2025-12-26',
                'estado' => 'proximo',
                'max_equipos' => 18,
                'categoria_id' => 1,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'nombre' => 'Ciberseguridad Hackathon',
                'descripcion' => 'Participa en desafíos de seguridad informática y protección de datos.',
                'fecha_inicio' => '2025-11-19',
                'fecha_fin' => '2025-11-21',
                'estado' => 'finalizado',
                'max_equipos' => 12,
                'categoria_id' => 1,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: criterio_evaluacion
        DB::table('criterio_evaluacion')->insert([
            0 => [
                'id' => 1,
                'evento_id' => 1,
                'nombre' => 'Innovación',
                'ponderacion' => 30,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'evento_id' => 1,
                'nombre' => 'Viabilidad Técnica',
                'ponderacion' => 40,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'evento_id' => 1,
                'nombre' => 'Presentación y Pitch',
                'ponderacion' => 30,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'evento_id' => 2,
                'nombre' => 'Diseño Visual',
                'ponderacion' => 35,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'evento_id' => 2,
                'nombre' => 'Usabilidad',
                'ponderacion' => 35,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'evento_id' => 2,
                'nombre' => 'Creatividad',
                'ponderacion' => 30,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'evento_id' => 3,
                'nombre' => 'Funcionalidad',
                'ponderacion' => 40,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'evento_id' => 3,
                'nombre' => 'Diseño UX',
                'ponderacion' => 30,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'evento_id' => 3,
                'nombre' => 'Innovación',
                'ponderacion' => 30,
                'created_at' => '2025-12-09 21:01:59',
                'updated_at' => '2025-12-09 21:01:59',
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: users
        DB::table('users')->insert([
            0 => [
                'id' => 1,
                'name' => 'Admin Innovatec',
                'email' => 'admin@innovatec.com',
                'email_verified_at' => '2025-12-09 21:02:00',
                'password' => '$2y$12$kTsd0FGDxDyfu5AVpnwTEelbZnuSg0zqQep3N.tq4Utoyr1mka4Ky',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            1 => [
                'id' => 2,
                'name' => 'Juan Perez',
                'email' => 'juan.perez@test.com',
                'email_verified_at' => '2025-12-09 21:02:00',
                'password' => '$2y$12$8rcpOev7QrJRe4qnW7TzHOtcQRD0L0hV10E9ZC2VenB1VvYEBywqS',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            2 => [
                'id' => 3,
                'name' => 'Angel Zarate',
                'email' => 'angelz@test.com',
                'email_verified_at' => '2025-12-09 21:02:00',
                'password' => '$2y$12$.JVd3sIO40/QjsZQJRBLWujF4kXrAb8WPN42xVhDSHTINwkPj62M2',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            3 => [
                'id' => 4,
                'name' => 'Maria Rodriguez',
                'email' => 'maria.rodriguez@test.com',
                'email_verified_at' => '2025-12-09 21:02:00',
                'password' => '$2y$12$Ntj650d9pVMIpbmmKOPN0u0iQ7IYfhrnB7lEH4CGObtLiucyd4IeK',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            4 => [
                'id' => 5,
                'name' => 'Carlos Mendez',
                'email' => 'carlos.mendez@test.com',
                'email_verified_at' => '2025-12-09 21:02:01',
                'password' => '$2y$12$pTvWRfeXz3moYaC0hHy.rOLZH5VeJtwOt2TA8jDQBxL0mCIpPE.fW',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            5 => [
                'id' => 6,
                'name' => 'Sofia Rodriguez',
                'email' => 'sofia.rodriguez@test.com',
                'email_verified_at' => '2025-12-09 21:02:01',
                'password' => '$2y$12$DRsKPqwWPGb2wXCZs.je0OYg69sl4VnmPIJ9GOTw7zzbg8wnYYpqy',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            6 => [
                'id' => 7,
                'name' => 'Miguel Torres',
                'email' => 'miguel.torres@test.com',
                'email_verified_at' => '2025-12-09 21:02:01',
                'password' => '$2y$12$43196Qggcp6FpJbVREZ.pOp5eNqzFUkQMlbyN7J04/8wvHQxXM0iG',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            7 => [
                'id' => 8,
                'name' => 'Laura Gomez',
                'email' => 'laura.gomez@test.com',
                'email_verified_at' => '2025-12-09 21:02:01',
                'password' => '$2y$12$yOwbsT4qhKSvC15Djyc4Oe012manHBRS.pXa78nPTZOgZB.NSPPNG',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            8 => [
                'id' => 9,
                'name' => 'Diego Martinez',
                'email' => 'diego.martinez@test.com',
                'email_verified_at' => '2025-12-09 21:02:01',
                'password' => '$2y$12$2NUrj02T5HUnzd4ERDj2YOl3RDxwLIOVLrAlFV0Z3.HkjaQYDW3ii',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            9 => [
                'id' => 10,
                'name' => 'Ana Hernandez',
                'email' => 'ana.hernandez@test.com',
                'email_verified_at' => '2025-12-09 21:02:02',
                'password' => '$2y$12$X06eyFWdFnDMmjYIKgLfSu4sZfsZRoI3FgdtlXqPazlve.XGl9pve',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            10 => [
                'id' => 11,
                'name' => 'Roberto Sanchez',
                'email' => 'roberto.sanchez@test.com',
                'email_verified_at' => '2025-12-09 21:02:02',
                'password' => '$2y$12$NOpqzTeZXWnd3qG2LQexXuATbuJIXmNThB56di3pB.V.VnUpvVHOS',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            11 => [
                'id' => 12,
                'name' => 'Patricia Lopez',
                'email' => 'patricia.lopez@test.com',
                'email_verified_at' => '2025-12-09 21:02:02',
                'password' => '$2y$12$VZjZ9z59K45BV1WXUmpNFel1n53diZS3scXwhTDyVCIlNNfYgd2m.',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            12 => [
                'id' => 13,
                'name' => 'Fernando Diaz',
                'email' => 'fernando.diaz@test.com',
                'email_verified_at' => '2025-12-09 21:02:02',
                'password' => '$2y$12$5nFbSFz.Ws9pu1C6K9i5d.jZu1IVdbtV/NsrkiEvWgvkX6PxTMFHm',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            13 => [
                'id' => 14,
                'name' => 'Gabriela Ramirez',
                'email' => 'gabriela.ramirez@test.com',
                'email_verified_at' => '2025-12-09 21:02:03',
                'password' => '$2y$12$3N2bXK9WrUfqEld.1sGuCOYgoWeqcy.4dsOjvkCyQGOASRIxrJk6G',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            14 => [
                'id' => 15,
                'name' => 'Luis Morales',
                'email' => 'luis.morales@test.com',
                'email_verified_at' => '2025-12-09 21:02:03',
                'password' => '$2y$12$WpquV/CUSp0IV.E4GBNSIOy8XjLYuFX0OeR9aZ2eba601misxGCIa',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            15 => [
                'id' => 16,
                'name' => 'Carmen Flores',
                'email' => 'carmen.flores@test.com',
                'email_verified_at' => '2025-12-09 21:02:03',
                'password' => '$2y$12$2yOHqe1gU/HiB8.v4Z6ZUeD45CaglaAT0MzMqF9NQgYX4uje9dgYW',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            16 => [
                'id' => 17,
                'name' => 'Jorge Castro',
                'email' => 'jorge.castro@test.com',
                'email_verified_at' => '2025-12-09 21:02:03',
                'password' => '$2y$12$O/t.ZcbLHt6/oGJypYV68.r2c4/tDGKXUzmJ7psQbld/izRArkyQK',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            17 => [
                'id' => 18,
                'name' => 'Monica Vargas',
                'email' => 'monica.vargas@test.com',
                'email_verified_at' => '2025-12-09 21:02:03',
                'password' => '$2y$12$/dG0a468JehsEw72f7ipMuD4vZOT5dhxGkM96wa352Q2yUrM8E.3q',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            18 => [
                'id' => 19,
                'name' => 'Ricardo Ortiz',
                'email' => 'ricardo.ortiz@test.com',
                'email_verified_at' => '2025-12-09 21:02:04',
                'password' => '$2y$12$DvlKkWQh3oWA7uQX44ob1OTB0xoOs9ziKP8Kh548j01yzX6Z.MDI6',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
            19 => [
                'id' => 20,
                'name' => 'Dr. Roberto Silva',
                'email' => 'roberto.silva@juez.com',
                'email_verified_at' => '2025-12-09 21:02:04',
                'password' => '$2y$12$UKEeFScY90eWYRCq/OtnK.ZptqWeZJL4AWaPAC.EHIr3sy5/DzouK',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
            20 => [
                'id' => 21,
                'name' => 'Dra. Ana Martinez',
                'email' => 'ana.martinez@juez.com',
                'email_verified_at' => '2025-12-09 21:02:04',
                'password' => '$2y$12$VUy.qxSHnOIhB5xuYTiLY.721pL6J4HAd7F3pVlSWvTonDabeIo32',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
            21 => [
                'id' => 22,
                'name' => 'Ing. Pedro Gonzalez',
                'email' => 'pedro.gonzalez@juez.com',
                'email_verified_at' => '2025-12-09 21:02:04',
                'password' => '$2y$12$gwcPRI78ptAT285UQ51Cf.cDanX4tpvULt6LNDUpvjrlVIRgBJh..',
                'verification_code' => NULL,
                'verification_code_expires_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
        ]);

        // Tabla: user_rol
        DB::table('user_rol')->insert([
            0 => [
                'user_id' => 1,
                'rol_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'user_id' => 2,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'user_id' => 3,
                'rol_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'user_id' => 4,
                'rol_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'user_id' => 5,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            5 => [
                'user_id' => 6,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            6 => [
                'user_id' => 7,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            7 => [
                'user_id' => 8,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            8 => [
                'user_id' => 9,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            9 => [
                'user_id' => 10,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            10 => [
                'user_id' => 11,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            11 => [
                'user_id' => 12,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            12 => [
                'user_id' => 13,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            13 => [
                'user_id' => 14,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            14 => [
                'user_id' => 15,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            15 => [
                'user_id' => 16,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            16 => [
                'user_id' => 17,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            17 => [
                'user_id' => 18,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            18 => [
                'user_id' => 19,
                'rol_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            19 => [
                'user_id' => 20,
                'rol_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            20 => [
                'user_id' => 21,
                'rol_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            21 => [
                'user_id' => 22,
                'rol_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);

        // Tabla: participantes
        DB::table('participantes')->insert([
            0 => [
                'user_id' => 2,
                'carrera_id' => 6,
                'matricula' => 'A12345678',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            1 => [
                'user_id' => 3,
                'carrera_id' => 6,
                'matricula' => 'JUEZ123',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            2 => [
                'user_id' => 4,
                'carrera_id' => 6,
                'matricula' => 'JUEZ456',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            3 => [
                'user_id' => 5,
                'carrera_id' => 6,
                'matricula' => 'A00123456',
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            4 => [
                'user_id' => 6,
                'carrera_id' => 6,
                'matricula' => 'A00123457',
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            5 => [
                'user_id' => 7,
                'carrera_id' => 6,
                'matricula' => 'A00123458',
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            6 => [
                'user_id' => 8,
                'carrera_id' => 6,
                'matricula' => 'A00123459',
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            7 => [
                'user_id' => 9,
                'carrera_id' => 6,
                'matricula' => 'A00123460',
                'created_at' => '2025-12-09 21:02:01',
                'updated_at' => '2025-12-09 21:02:01',
            ],
            8 => [
                'user_id' => 10,
                'carrera_id' => 6,
                'matricula' => 'A00123461',
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            9 => [
                'user_id' => 11,
                'carrera_id' => 6,
                'matricula' => 'A00123462',
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            10 => [
                'user_id' => 12,
                'carrera_id' => 6,
                'matricula' => 'A00123463',
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            11 => [
                'user_id' => 13,
                'carrera_id' => 6,
                'matricula' => 'A00123464',
                'created_at' => '2025-12-09 21:02:02',
                'updated_at' => '2025-12-09 21:02:02',
            ],
            12 => [
                'user_id' => 14,
                'carrera_id' => 6,
                'matricula' => 'A00123465',
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            13 => [
                'user_id' => 15,
                'carrera_id' => 6,
                'matricula' => 'A00123466',
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            14 => [
                'user_id' => 16,
                'carrera_id' => 6,
                'matricula' => 'A00123467',
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            15 => [
                'user_id' => 17,
                'carrera_id' => 6,
                'matricula' => 'A00123468',
                'created_at' => '2025-12-09 21:02:03',
                'updated_at' => '2025-12-09 21:02:03',
            ],
            16 => [
                'user_id' => 18,
                'carrera_id' => 6,
                'matricula' => 'A00123469',
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
            17 => [
                'user_id' => 19,
                'carrera_id' => 6,
                'matricula' => 'A00123470',
                'created_at' => '2025-12-09 21:02:04',
                'updated_at' => '2025-12-09 21:02:04',
            ],
        ]);

        // Tabla: evento_participante
        DB::table('evento_participante')->insert([
            0 => [
                'evento_id' => 1,
                'participante_id' => 2,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            1 => [
                'evento_id' => 1,
                'participante_id' => 3,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
            2 => [
                'evento_id' => 1,
                'participante_id' => 4,
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
            ],
        ]);

        // Tabla: constancias
        DB::table('constancias')->insert([
            0 => [
                'id' => 1,
                'participante_id' => 2,
                'evento_id' => 1,
                'tipo' => 'participacion',
                'lugar' => NULL,
                'archivo_path' => 'constancias/constancia-ejemplo.pdf',
                'codigo_qr' => 'bfcf4dd1-2bb8-4244-a6f4-662961c03ea4',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'participante_id' => 3,
                'evento_id' => 1,
                'tipo' => 'participacion',
                'lugar' => NULL,
                'archivo_path' => 'constancias/constancia-ejemplo.pdf',
                'codigo_qr' => '2b58bb38-4e92-4098-bf57-3d0d55b1bf44',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'participante_id' => 4,
                'evento_id' => 1,
                'tipo' => 'participacion',
                'lugar' => NULL,
                'archivo_path' => 'constancias/constancia-ejemplo.pdf',
                'codigo_qr' => '8ceba504-675c-42b9-b492-4511e641a8ab',
                'created_at' => '2025-12-09 21:02:00',
                'updated_at' => '2025-12-09 21:02:00',
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: equipos
        DB::table('equipos')->insert([
            0 => [
                'id' => 1,
                'nombre' => 'Team Alpha',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
                'evento_id' => NULL,
                'es_publico' => 1,
            ],
            1 => [
                'id' => 2,
                'nombre' => 'Innovators Hub',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
                'evento_id' => NULL,
                'es_publico' => 1,
            ],
            2 => [
                'id' => 3,
                'nombre' => 'Code Warriors',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
                'evento_id' => NULL,
                'es_publico' => 1,
            ],
            3 => [
                'id' => 4,
                'nombre' => 'Tech Pioneers',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
                'evento_id' => NULL,
                'es_publico' => 1,
            ],
            4 => [
                'id' => 5,
                'nombre' => 'Digital Minds',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
                'evento_id' => NULL,
                'es_publico' => 1,
            ],
            5 => [
                'id' => 6,
                'nombre' => 'los boings',
                'logo_path' => 'equipos/p5CVM0UFjnxdeVLtQaYVahwnY5gjabeE1e4XDYDH.jpg',
                'created_at' => '2025-12-09 22:25:55',
                'updated_at' => '2025-12-09 22:25:55',
                'deleted_at' => NULL,
                'evento_id' => 1,
                'es_publico' => 1,
            ],
            6 => [
                'id' => 7,
                'nombre' => 'pelados',
                'logo_path' => NULL,
                'created_at' => '2025-12-09 22:30:13',
                'updated_at' => '2025-12-09 22:30:13',
                'deleted_at' => NULL,
                'evento_id' => 4,
                'es_publico' => 0,
            ],
        ]);

        // Tabla: equipo_participante
        DB::table('equipo_participante')->insert([
            0 => [
                'equipo_id' => 1,
                'participante_id' => 2,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'equipo_id' => 1,
                'participante_id' => 3,
                'perfil_id' => 2,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'equipo_id' => 1,
                'participante_id' => 4,
                'perfil_id' => 3,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'equipo_id' => 2,
                'participante_id' => 5,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'equipo_id' => 2,
                'participante_id' => 6,
                'perfil_id' => 2,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            5 => [
                'equipo_id' => 2,
                'participante_id' => 7,
                'perfil_id' => 3,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            6 => [
                'equipo_id' => 2,
                'participante_id' => 8,
                'perfil_id' => 4,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            7 => [
                'equipo_id' => 3,
                'participante_id' => 9,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            8 => [
                'equipo_id' => 3,
                'participante_id' => 10,
                'perfil_id' => 2,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            9 => [
                'equipo_id' => 3,
                'participante_id' => 11,
                'perfil_id' => 3,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            10 => [
                'equipo_id' => 4,
                'participante_id' => 12,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            11 => [
                'equipo_id' => 4,
                'participante_id' => 13,
                'perfil_id' => 2,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            12 => [
                'equipo_id' => 4,
                'participante_id' => 14,
                'perfil_id' => 3,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            13 => [
                'equipo_id' => 4,
                'participante_id' => 15,
                'perfil_id' => 4,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            14 => [
                'equipo_id' => 5,
                'participante_id' => 16,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            15 => [
                'equipo_id' => 5,
                'participante_id' => 17,
                'perfil_id' => 4,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            16 => [
                'equipo_id' => 5,
                'participante_id' => 18,
                'perfil_id' => 3,
                'es_lider' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            17 => [
                'equipo_id' => 6,
                'participante_id' => 2,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => '2025-12-09 22:25:55',
                'updated_at' => '2025-12-09 22:25:55',
            ],
            18 => [
                'equipo_id' => 7,
                'participante_id' => 2,
                'perfil_id' => 1,
                'es_lider' => 1,
                'created_at' => '2025-12-09 22:30:13',
                'updated_at' => '2025-12-09 22:30:13',
            ],
        ]);

        // Tabla: proyectos
        DB::table('proyectos')->insert([
            0 => [
                'id' => 1,
                'equipo_id' => 1,
                'evento_id' => 1,
                'categoria_id' => NULL,
                'titulo' => 'App de monitoreo energético',
                'resumen' => 'Aplicación web para visualizar el consumo energético en tiempo real del campus.',
                'link_repositorio' => 'https://github.com/team-alpha/monitoreo',
                'imagen_path' => NULL,
                'documento_path' => NULL,
                'estado' => 'en_desarrollo',
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'equipo_id' => 2,
                'evento_id' => 1,
                'categoria_id' => NULL,
                'titulo' => 'Sistema de sensores IoT para aulas',
                'resumen' => 'Red de sensores para monitorear temperatura, humedad y ocupación de las aulas.',
                'link_repositorio' => 'https://github.com/innovators/iot-aulas',
                'imagen_path' => NULL,
                'documento_path' => NULL,
                'estado' => 'en_desarrollo',
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'equipo_id' => 3,
                'evento_id' => 3,
                'categoria_id' => NULL,
                'titulo' => 'App móvil de gestión de tareas estudiantiles',
                'resumen' => 'Aplicación para organizar tareas, horarios y eventos académicos.',
                'link_repositorio' => 'https://github.com/codewarriors/taskapp',
                'imagen_path' => NULL,
                'documento_path' => NULL,
                'estado' => 'en_desarrollo',
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'equipo_id' => 4,
                'evento_id' => 3,
                'categoria_id' => NULL,
                'titulo' => 'Plataforma de intercambio de libros',
                'resumen' => 'App móvil para facilitar el préstamo e intercambio de libros entre estudiantes.',
                'link_repositorio' => 'https://github.com/techpioneers/bookshare',
                'imagen_path' => NULL,
                'documento_path' => NULL,
                'estado' => 'terminado',
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'equipo_id' => 5,
                'evento_id' => 2,
                'categoria_id' => NULL,
                'titulo' => 'Rediseño de portal estudiantil',
                'resumen' => 'Nueva interfaz intuitiva para el sistema de servicios estudiantiles.',
                'link_repositorio' => 'https://github.com/digitalminds/portal-ui',
                'imagen_path' => NULL,
                'documento_path' => NULL,
                'estado' => 'calificado',
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: avances
        DB::table('avances')->insert([
            0 => [
                'id' => 1,
                'proyecto_id' => 1,
                'descripcion' => 'Avance 1: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-11-30',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'proyecto_id' => 1,
                'descripcion' => 'Avance 2: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-03',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'proyecto_id' => 1,
                'descripcion' => 'Avance 3: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-06',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'proyecto_id' => 2,
                'descripcion' => 'Avance 1: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-03',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'proyecto_id' => 2,
                'descripcion' => 'Avance 2: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-06',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'proyecto_id' => 3,
                'descripcion' => 'Avance 1: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-03',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'proyecto_id' => 3,
                'descripcion' => 'Avance 2: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-06',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'proyecto_id' => 4,
                'descripcion' => 'Avance 1: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-11-30',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'proyecto_id' => 4,
                'descripcion' => 'Avance 2: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-03',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            9 => [
                'id' => 10,
                'proyecto_id' => 4,
                'descripcion' => 'Avance 3: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-06',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            10 => [
                'id' => 11,
                'proyecto_id' => 5,
                'descripcion' => 'Avance 1: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-11-27',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            11 => [
                'id' => 12,
                'proyecto_id' => 5,
                'descripcion' => 'Avance 2: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-11-30',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            12 => [
                'id' => 13,
                'proyecto_id' => 5,
                'descripcion' => 'Avance 3: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-03',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
            13 => [
                'id' => 14,
                'proyecto_id' => 5,
                'descripcion' => 'Avance 4: Progreso en el desarrollo del proyecto.',
                'archivo_path' => NULL,
                'fecha' => '2025-12-06',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: calificaciones
        DB::table('calificaciones')->insert([
            0 => [
                'id' => 1,
                'proyecto_id' => 1,
                'juez_user_id' => 3,
                'criterio_id' => 1,
                'puntuacion' => 80,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'proyecto_id' => 1,
                'juez_user_id' => 4,
                'criterio_id' => 1,
                'puntuacion' => 86,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'proyecto_id' => 1,
                'juez_user_id' => 3,
                'criterio_id' => 2,
                'puntuacion' => 100,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'proyecto_id' => 1,
                'juez_user_id' => 4,
                'criterio_id' => 2,
                'puntuacion' => 72,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'proyecto_id' => 1,
                'juez_user_id' => 3,
                'criterio_id' => 3,
                'puntuacion' => 80,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'proyecto_id' => 1,
                'juez_user_id' => 4,
                'criterio_id' => 3,
                'puntuacion' => 99,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'proyecto_id' => 2,
                'juez_user_id' => 3,
                'criterio_id' => 1,
                'puntuacion' => 92,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'proyecto_id' => 2,
                'juez_user_id' => 4,
                'criterio_id' => 1,
                'puntuacion' => 74,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'proyecto_id' => 2,
                'juez_user_id' => 3,
                'criterio_id' => 2,
                'puntuacion' => 97,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            9 => [
                'id' => 10,
                'proyecto_id' => 2,
                'juez_user_id' => 4,
                'criterio_id' => 2,
                'puntuacion' => 75,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            10 => [
                'id' => 11,
                'proyecto_id' => 2,
                'juez_user_id' => 3,
                'criterio_id' => 3,
                'puntuacion' => 96,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            11 => [
                'id' => 12,
                'proyecto_id' => 2,
                'juez_user_id' => 4,
                'criterio_id' => 3,
                'puntuacion' => 70,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            12 => [
                'id' => 13,
                'proyecto_id' => 3,
                'juez_user_id' => 3,
                'criterio_id' => 7,
                'puntuacion' => 82,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            13 => [
                'id' => 14,
                'proyecto_id' => 3,
                'juez_user_id' => 4,
                'criterio_id' => 7,
                'puntuacion' => 79,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            14 => [
                'id' => 15,
                'proyecto_id' => 3,
                'juez_user_id' => 3,
                'criterio_id' => 8,
                'puntuacion' => 84,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            15 => [
                'id' => 16,
                'proyecto_id' => 3,
                'juez_user_id' => 4,
                'criterio_id' => 8,
                'puntuacion' => 72,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            16 => [
                'id' => 17,
                'proyecto_id' => 3,
                'juez_user_id' => 3,
                'criterio_id' => 9,
                'puntuacion' => 82,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            17 => [
                'id' => 18,
                'proyecto_id' => 3,
                'juez_user_id' => 4,
                'criterio_id' => 9,
                'puntuacion' => 79,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            18 => [
                'id' => 19,
                'proyecto_id' => 4,
                'juez_user_id' => 3,
                'criterio_id' => 7,
                'puntuacion' => 75,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            19 => [
                'id' => 20,
                'proyecto_id' => 4,
                'juez_user_id' => 4,
                'criterio_id' => 7,
                'puntuacion' => 82,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            20 => [
                'id' => 21,
                'proyecto_id' => 4,
                'juez_user_id' => 3,
                'criterio_id' => 8,
                'puntuacion' => 80,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            21 => [
                'id' => 22,
                'proyecto_id' => 4,
                'juez_user_id' => 4,
                'criterio_id' => 8,
                'puntuacion' => 80,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            22 => [
                'id' => 23,
                'proyecto_id' => 4,
                'juez_user_id' => 3,
                'criterio_id' => 9,
                'puntuacion' => 100,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            23 => [
                'id' => 24,
                'proyecto_id' => 4,
                'juez_user_id' => 4,
                'criterio_id' => 9,
                'puntuacion' => 86,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            24 => [
                'id' => 25,
                'proyecto_id' => 5,
                'juez_user_id' => 3,
                'criterio_id' => 4,
                'puntuacion' => 98,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            25 => [
                'id' => 26,
                'proyecto_id' => 5,
                'juez_user_id' => 4,
                'criterio_id' => 4,
                'puntuacion' => 85,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            26 => [
                'id' => 27,
                'proyecto_id' => 5,
                'juez_user_id' => 3,
                'criterio_id' => 5,
                'puntuacion' => 91,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            27 => [
                'id' => 28,
                'proyecto_id' => 5,
                'juez_user_id' => 4,
                'criterio_id' => 5,
                'puntuacion' => 86,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            28 => [
                'id' => 29,
                'proyecto_id' => 5,
                'juez_user_id' => 3,
                'criterio_id' => 6,
                'puntuacion' => 81,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
            29 => [
                'id' => 30,
                'proyecto_id' => 5,
                'juez_user_id' => 4,
                'criterio_id' => 6,
                'puntuacion' => 73,
                'created_at' => '2025-12-09 21:02:05',
                'updated_at' => '2025-12-09 21:02:05',
                'deleted_at' => NULL,
            ],
        ]);

        // Tabla: proyecto_juez
        DB::table('proyecto_juez')->insert([
            0 => [
                'id' => 1,
                'proyecto_id' => 4,
                'juez_user_id' => 4,
                'asignado_en' => '2025-12-09 15:08:31',
                'created_at' => '2025-12-09 21:08:31',
                'updated_at' => '2025-12-09 21:08:31',
            ],
        ]);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}